<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Copyright>Copyright © 2026 Gavin Xue</Copyright>
    <AssemblyTitle>Memo</AssemblyTitle>
    <Product>Memo</Product>
    <Version>1.0.0.1</Version>
    <FileVersion>1.0.0.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="NAudio.Wasapi" Version="3.1.0" />
  </ItemGroup>

</Project>
